version: '3.4'

services:
    geocodificador:
        build:
            context: .
            dockerfile: Dockerfile
        image: apigeo-geocodificador
        ports:
            - 5672:5672
        restart: on-failure 
        command: /bin/sh -c "while sleep 1000; do :; done"       
        depends_on:
            - rabbitmq
    rabbitmq: # login guest:guest
        image: rabbitmq:3.7-management
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=Andreani
            - RABBITMQ_DEFAULT_PASS=GeoApi
        ports:
            - "5672:5672"
    