USE [master]
GO

CREATE DATABASE [API_GEO_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'API_GEO_DB', FILENAME = N'C:\DB\API_GEO_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'API_GEO_DB_log', FILENAME = N'C:\DB\API_GEO_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [API_GEO_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [API_GEO_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [API_GEO_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [API_GEO_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [API_GEO_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [API_GEO_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [API_GEO_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [API_GEO_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [API_GEO_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [API_GEO_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [API_GEO_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [API_GEO_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [API_GEO_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [API_GEO_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [API_GEO_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [API_GEO_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [API_GEO_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [API_GEO_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [API_GEO_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [API_GEO_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [API_GEO_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [API_GEO_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [API_GEO_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [API_GEO_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [API_GEO_DB] SET  MULTI_USER 
GO

ALTER DATABASE [API_GEO_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [API_GEO_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [API_GEO_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [API_GEO_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [API_GEO_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [API_GEO_DB] SET QUERY_STORE = OFF
GO

USE [API_GEO_DB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [API_GEO_DB] SET  READ_WRITE 
GO

USE [API_GEO_DB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LocalizadorData](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[latitud] [float] NULL,
	[longitud] [float] NULL,
	[estado] [varchar](50) NULL,
	[calle] [varchar](100) NOT NULL,
	[numero] [int] NOT NULL,
	[ciudad] [varchar](100) NOT NULL,
	[codigo_postal] [varchar](20) NOT NULL,
	[provincia] [varchar](100) NOT NULL,
	[pais] [varchar](100) NOT NULL,
 CONSTRAINT [PK_LocalizadorData] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO