version: "3.5"
services:
    db:
        build: 
            context: ./Db
            dockerfile: Dockerfile
        ports:
            - "1433:1433"
        tty: true
        networks:
            - localdev
    app:
        build: .
        ports:
            - "5001:5001"
        networks:
            - localdev
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
networks:
    localdev:
        driver: bridge