version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
            - "5001:5001"
            - "5672:5672"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "APIGEO"
            ACCEPT_EULA: "Y"